# Generated by Django 2.0.2 on 2018-06-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('product_id', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('rate', models.IntegerField()),
                ('amazon_rate', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
