# Generated by Django 2.0.2 on 2018-06-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data',
            new_name='date',
        ),
    ]
