# Generated by Django 2.0.2 on 2018-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20180627_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(),
        ),
    ]
