# Generated by Django 2.0.2 on 2018-06-28 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20180627_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 28, 15, 20, 27, 685496)),
        ),
    ]
