# Generated by Django 2.0.2 on 2018-06-28 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_auto_20180628_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 28, 20, 18, 10, 394647, tzinfo=utc)),
        ),
    ]
