# Generated by Django 2.0.2 on 2018-06-28 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20180628_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2014, 12, 4)),
        ),
    ]
