# Generated by Django 2.0.2 on 2018-06-28 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20180628_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2018, 6, 28)),
        ),
    ]
