# Generated by Django 2.0.2 on 2018-06-28 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_auto_20180628_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
