# Generated by Django 2.0.2 on 2018-06-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0017_auto_20180628_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=None, max_length=900),
        ),
    ]
